name: Install

on:
  workflow_call:

jobs:
  # Use to pre-fill the cache for install & packages
  # Sightly optimizing furthers tests speed & ensure constistent env
  install:
    runs-on: ubuntu-latest
    steps:
      # Required before a local composite action
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Bun install
        uses: ./.github/actions/bun-install
