name: Maths

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: my-project
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Bun install
        uses: ./.github/actions/bun-install

      - name: Run maths tests
        run: bun test addition.test.ts multiplication.test.ts division.test.ts
