name: Run Tests

# Les tests sont triggers quand..
on:
  push:
  pull_request:
  # Permet de déclencher le workflow manuellement
  workflow_dispatch:

# Jobs peut être une liste de jobs, pas forcément un seul
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: my-project
    # Installation & packages
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.21

      - name: Install dependencies
        run: bun install

      # Lancement du script contenu dans package.json
      - name: Run tests
        run: bun test
